### ISSUE TITLE
Tray Icon Invisible

### ISSUE THREAD

**Issue by AaronC31** [kelyvin/Google-Messages-For-Desktop#23]
When using the version that's able to be minimized to the tray, the app is there but the icon is invisible.

**Comment by mgjuhler** [comment]
I have the same issue.

**Comment by pbanj** [comment]
i had fixed this issue. but it seems to have come back up and even on my end the icon is gone again

**Comment by 0msLaw** [comment]
@pbanj found any solution to the issue?

**Comment by pbanj** [comment]
i just had time to mess with it and got it working again. ill make a pr in a moment

**Comment by pbanj** [comment]
#25 fixes it. seems the icon was in the wrong place. to manually fix it move icon.ico from `\resources` to `\resources\app` then restart the program

**Comment by AaronC31** [comment]
Even though it's not your job to fix it, I appreciate you actually doing that!

**Comment by kelyvin** [comment]
Thanks @pbanj for implementing the fix! I have merged in your changes and updated the release. https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.1.2

**Comment by pbanj** [comment]
> 
> 
> Even though it's not your job to fix it, I appreciate you actually doing that!

i dont mind it lol



> 
> 
> Thanks @pbanj for implementing the fix! I have merged in your changes and updated the release. https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.1.2

no prob

**Comment by MellowPhi** [comment]
@pbanj Thanks, it worked out for me. Cheers
