### ISSUE TITLE
Windows notifications do not work. (appreciate the work you guys are doing, its a great app)

### ISSUE THREAD

**Issue by fghjgsrhsdes3456** [kelyvin/Google-Messages-For-Desktop#26]

**Comment by swa-dev** [comment]
These were working for me, until I accidently told Windows not to display notifications. Now I can't get them back. The app doesn't show up in the "Turn app notifications on or off" section of Windows 10. I've went through the registry and cleared out any references that I could find to this application and still have no luck.

**Comment by kelyvin** [comment]
Hi everyone, thanks for your continued patience. This should be resolved with the latest version here: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.2.0

Let me know if that addresses all your issues, and if so, I will close this out. Thanks!

**Comment by swa-dev** [comment]
Amazing! Works like a charm now! I do not see the application in the Notifications & Actions Settings, but it still works, nonetheless. Great job on this application!
