### ISSUE TITLE
Opening the app says to update browswer when all are updated

### ISSUE THREAD

**Issue by wrasmu** [kelyvin/Google-Messages-For-Desktop#29]
This started just recently so i haven't figured out if it was something that i did on my computer or not just yet. But when i try to open the android messages.exe app it opens the window like its going to work and then all i get is the window says "Please update your browser" with other stuff stating that i'm using an out of date browser. I have verified that ALL of my browsers are up to date so i'm not sure how to resolve this. Here is an image of what i see when i try to open the app. Hopefully i can get it resolved because i love this app and use it daily. 

![image](https://user-images.githubusercontent.com/77136615/103972327-659dff00-5132-11eb-885e-27664260d0d1.png)

**Comment by wrasmu** [comment]
Forgot to add that i am using the windows version. windows 10 64 bit

**Comment by Koolstr** [comment]
Same issue. Seems like a simple fix, can we get a hotfix for this at least?

**Comment by pigeottoottoegip** [comment]
Same!

**Comment by ccastellon88** [comment]
Also have this issue just noticed it about 30minutes  ago. i thought maybe i just needed to reinstall/update it but no dice

**Comment by mrpcakes** [comment]
same here this morning. did double check and my chrome does have a new update but that did not fix the software: 
Version 87.0.4280.141 (Official Build) (64-bit)
must have happened overnight as 5 hours ago it was working fine.

**Comment by alyter** [comment]
Same here

**Comment by mercplus** [comment]
Same on MacOS Big Sur, 11.1

**Comment by hyd3sec** [comment]
Same issue here on Win10 x64, just started happening

**Comment by viviann16** [comment]
Same issue on macOS Catalina 10.15.7, Chrome is fully updated.

**Comment by clarklwilliamson** [comment]
I assume it is using an embedded chrome, is there a way to just update that?

**Comment by roberthchan** [comment]
Same MacOS Mojave 10.14.6

**Comment by Synderryn** [comment]
Same issue. Windows 10 x64. Noticed it today (Sat Jan 9th) after a pc reboot.

**Comment by alyter** [comment]
I think the problem lies with nativefier. My buddy had the exact same thing happen to his whatsapp desktop app which also uses nativefier.

**Comment by brandfluke** [comment]
Same here!

**Comment by ch0rn** [comment]
Same Issue here.

**Comment by kelyvin** [comment]
Hi everyone, thanks for your continued patience. This should be resolved with the latest version here: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.2.0

Let me know if that addresses all your issues, and if so, I will close this out. Thanks!

**Comment by viviann16** [comment]
Just downloaded it on my Macbook (macOS Catalina 10.15.7), and it worked for me. Thank you so much for fixing it so quickly!!

**Comment by wrasmu** [comment]
Just and update i downloaded the most recent update that was posted and it does appear to be working, text sent from and to with no issues.

**Comment by kelyvin** [comment]
@viviann16 @wrasmu awesome to hear! I will close this issue then and folks can reopen if the issue persists. Thanks everyone!

**Comment by sam-randolph** [comment]
Is the new version working for anyone on Linux? I'm trying to run it on Linux Mint, but the executable seems to be missing from the v1.2.0 release directory (both precompiled and when recompiled from source manually).

**Comment by VOOM108** [comment]
I get a similar issue using 1.3.0 on Windows 10.... This appears on every start of the program. After clicking ok, the app works
![nativefier](https://user-images.githubusercontent.com/16562946/136232127-c5779529-834f-4db0-ab25-8474daf5a101.png)
.
