### ISSUE TITLE
Notifications don't work.

### ISSUE THREAD

**Issue by Eagle1337** [kelyvin/Google-Messages-For-Desktop#3]
Windows 10 april update. I don't get any  notifications from the app,

**Comment by cevour** [comment]
Same here I don't get anything.

**Comment by RacingJayson** [comment]
"Notifications on Windows
To receive notifications on Windows, you'll need to do the following:

Add a shortcut of this app to the Start Menu folder
In the "Windows Settings" app, check if the setting for "Show notifications in action center" is on (It might be off by default)"

**Comment by Eagle1337** [comment]
already did that.

**Comment by breakthestatic** [comment]
I can't get notifications working either.  I noticed that although my shortcut is a tile on the start menu, it does NOT render in the list of all apps on the left hand side.  Perhaps that has something to do with it?  If so, does anyone know a way to move the shortcut to all apps?  I already tried adding it to %appdata%\Microsoft\Windows\Start Menu\Programs, but it will not show up there (only the tile on the right side).

**Comment by EddJack** [comment]
Any updates on how to get notifications running again?

**Comment by KRGuyton** [comment]
Notifications do not work as of 8/7.  Added shortcut to Start menu folder.

**Comment by kelyvin** [comment]
Potentially resolved in https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.2.0
