### ISSUE TITLE
Old build detected error 

### ISSUE THREAD

**Issue by mrpcakes** [kelyvin/Google-Messages-For-Desktop#33]
Not sure how big of an issue this is as the app still works.

Error popped up this morning for me on windows 10

![image](https://user-images.githubusercontent.com/31196392/111462894-f70a8e00-86ec-11eb-83ad-3e3564eff2a4.png)

**Comment by kelyvin** [comment]
Eee yikes. I will try to take a look at this over the weekend and get a build out that resolves this.

**Comment by kelyvin** [comment]
@mrpcakes Thanks for your patience! You can download the latest versions here:
https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.3.0

**Comment by charlesspivak1** [comment]
Hey Kelyvin...I used the above link for it and it still gives the "old build detected" popup.  I'm afraid maybe I'm doing something wrong maybe?  Any suggestions?

**Comment by OhByteMe** [comment]
Nope, you're not @charlesspivak1 .... I'm getting the exact same thing but on the Mac platform. Could you please update the app?

**Comment by nk8020** [comment]
Same problem with the v1.3 now.
Somehow it seems that the way to go is making it not ask itself if this is its latest version.

**Comment by barrettwhiteman** [comment]
A year later and I am getting this problem too, just recently though.  Anyone figure out a fix here?

**Comment by mrpcakes** [comment]
honestly no unless you rebuild it.  I started to use windows phone link,  its OK but mainly didnt want to deal with the errors.
