### ISSUE TITLE
its update time again :-(

### ISSUE THREAD

**Issue by mrpcakes** [kelyvin/Google-Messages-For-Desktop#40]
Sadly its that time again where the app needs to be updated.
Please and thank you.

If you provide instructions on how i am more than willing to keep it going

**Comment by dkfurrow** [comment]
@mrpcakes please see my pull request with updated build...I  have tested the windows and linux versions...I don't use a mac so can't really speak to that--if you try that zipfile, please let me know if it works.
Thanks,
Dale

**Comment by mrpcakes** [comment]
@dkfurrow  yep i downloaded the windows zip file however needed to rename it from ,zip to .zip.
it does work 👍

**Comment by dkfurrow** [comment]
@mrpcakes I know I'm getting old when I can't tell a comma from a period!  Fixed filenames in latest push.  Thanks for the note, glad it's working for you.

**Comment by martin-braun** [comment]
Or just build it yourself. Just install node.js and then: 

```bash
sudo npm i nativefier -D -f -g
```

Then in a new Terminal: 
```bash
ua=$(curl -s https://whatmyuseragent.com/browser/chrome/ch | tac | tac | grep -o -m 1 'Mozilla[^"<]\+' | head -n1)
nativefier -n "Google Messages" "messages.google.com/web" -u \"$ua\" --internal-urls \".*accounts.google.com.*|remotedesktop.google.com/access/\" --single-instance
```

**Comment by kelyvin** [comment]
Sorry for the delay, should be resolved now: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.4.2 

To prevent this from happening often, will need someone's help in the following request: https://github.com/kelyvin/Google-Messages-For-Desktop/issues/36
