### ISSUE TITLE
Old Build Dectected - Mac

### ISSUE THREAD

**Issue by colsartoris** [kelyvin/Google-Messages-For-Desktop#43]
Have been getting an Old Build Detected error on my Mac for awhile. I know that #40 describes a similar issue for Windows. I have just been checking back in to see if the build has been updated for a month or so, but hadn't seen it updated or reported, so I figured I'd log an issue. Thanks so much for this great work!

**Comment by kelyvin** [comment]
Sorry for the delay, should be resolved now: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.4.2 

To prevent this from happening often, will need someone's help in the following request: https://github.com/kelyvin/Google-Messages-For-Desktop/issues/36
