### ISSUE TITLE
Google Messages Launcher is launching popups with a-znachrichten.com in the URL.

### ISSUE THREAD

**Issue by connorwaldo** [kelyvin/Google-Messages-For-Desktop#46]
I attached screenshots of what happens...it'll go to https://a-znachrichten.com/ (or a-znachrichten )

![Screenshot 2021-08-17 091107](https://user-images.githubusercontent.com/8463074/129951581-80588ca4-fc95-4cdd-8fbe-ad4cc86e7abc.png)

then it'll redirect to whatever website I'm on and have a weird URL (i.e., flowerandgardenideas.com).
![Screenshot 2021-08-16 120630](https://user-images.githubusercontent.com/8463074/129951580-78e12a5f-a5fe-41a4-bac3-6775e4f04c78.png)

Based on these threads, it appears to be your plugin:

1. https://forums.malwarebytes.com/topic/276907-a-znachrichtencom-creates-new-chrome-browser-window-on-some-links/?do=findComment&comment=1470919
2. https://www.reddit.com/r/chrome/comments/opiph5/random_popups_caused_by_google_messages_launcher/
3. https://www.reddit.com/r/chrome/comments/jgt3d4/chrome_is_opening_seemingly_random_hidden_tabs_on/

This just started a month ago. Any idea why?

**Comment by mkfink** [comment]
Yeah, I've been seeing the same popups for a few weeks using the version of this plugin that I got from the chrome web store. It seems this plugin has been removed from the store now.

Thanks to a [redditor in one of those threads](https://www.reddit.com/r/chrome/comments/opiph5/random_popups_caused_by_google_messages_launcher/h8cupm6?utm_source=share&utm_medium=web2x&context=3) for pointing out that the web version of google messages already has a desktop client of a sort. If you go to https://messages.google.com/web/ in Chrome, on the right end of the address bar there's an Install App button.

So now, as far I can tell, the program in this repo is redundant adware and should be avoided.

**Comment by pbanj** [comment]
or hear me out. this isnt a chrome extension, never has been. this is a stand alone program. this is messages for desktop. not messages launcher. you have the wrong repository 

this program

![image](https://user-images.githubusercontent.com/17306233/132274154-7e88beaa-9c72-42bc-8ae0-2c6209d6990a.png)

**Comment by mkfink** [comment]
@pbanj I'm really sorry, I thought this was the same project as the chrome extension (which is no longer listed in the Chrome Web Store, must have been taken down within the past month). I should have looked more closely before agreeing with @connorwaldo
