### ISSUE TITLE
Old build detected (Windows 10) - caused machine to freeze!

### ISSUE THREAD

**Issue by davidrbrake** [kelyvin/Google-Messages-For-Desktop#50]
I installed the latest Windows version (well, unzipped and launched the exe from within the windows folder) and got the attached error message. My machine locked up and I had to reboot. ![IMG_20220117_142901](https://user-images.githubusercontent.com/67521552/149819437-501f5a7a-8436-4d67-942a-fdc731d6bf09.jpg)

**Comment by nk8020** [comment]
There was an update in one of the forks of the windows (1.3) version, which with the version not appended, that still works, without issuing this message.
I'm not sure if I downloaded it from here:
https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.3.0
or another source, but I did replace the updated files and it works (even for windows 11).

**Comment by davidrbrake** [comment]
Unfortunately, the version I downloaded from here https://github.com/kelyvin/Google-Messages-For-Desktop/releases/download/v1.3.0/google-message-windows_v1.3.0.zip via here https://www.messagesfordesktop.com/ is the one that gave me that error.

**Comment by CeBotics** [comment]
I've just started seeing this startup message also.  Right after the last Windows update run.

**Comment by h3blatyl** [comment]
It's this one :) It's too bad this isn't the main one that comes up because it's still being updated. 

https://github.com/OrangeDrangon/android-messages-desktop

**Comment by pbanj** [comment]
there is also this https://github.com/kelyvin/Google-Messages-For-Desktop/issues/47

**Comment by kelyvin** [comment]
Sorry for the delay everyone. The latest version should now be available here: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.4.0
