### ISSUE TITLE
New -Old issue : "Old version detected". It took almost a year, but I got the message again (Win ver)

### ISSUE THREAD

**Issue by nk8020** [kelyvin/Google-Messages-For-Desktop#57]
New -Old issue : "Old version detected". It took almost a year, but I got the message again (Win ver)
It DOES operate very well on Win 11  - for interested parties..

**Comment by Ache07x** [comment]
This happened on my Mac app as well. Do I need to worry about this?

**Comment by nk8020** [comment]
> This happened on my Mac app as well. Do I need to worry about this?

It still works, so I basically am ignoring the comment, but i would rather not get it at all..

**Comment by notaclue2** [comment]
I am overjoyed to find this app to replace one that no longer works. However, I also received the "old build detected" notice upon opening the app. I have a macbook pro running OSX 10.11.6. I have apps for work that won't run on newer systems. The app seems to work, but I try not to run apps with security warnings. Would you please update the app or can someone explain (very simply) how I use the other files to correct the issue. Thank you.

<img width="426" alt="Screen Shot 2022-04-03 at 9 52 05 PM" src="https://user-images.githubusercontent.com/102942860/161481037-57da49b7-26a9-4b6c-a58a-4127bd00e559.png">

**Comment by kdumovic** [comment]
Saw this on startup as well (on Mac) --
<img width="1266" alt="Screen Shot 2022-04-05 at 11 07 18 AM" src="https://user-images.githubusercontent.com/4503680/161821635-01cf7246-6997-4656-85c8-3f637e98be33.png">

**Comment by pbanj** [comment]
https://github.com/kelyvin/Google-Messages-For-Desktop/issues/47

**Comment by kelyvin** [comment]
Sorry for the delay everyone. The latest version should now be available here: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.4.0
