### ISSUE TITLE
Not displaying text 

### ISSUE THREAD

**Issue by infool7** [kelyvin/Google-Messages-For-Desktop#59]
The app is connecting ok and can even send messages but it's not displaying text for any of the messages

**Comment by Nicabus** [comment]
I'm having the same issue.

**Comment by infool7** [comment]
> 
Ya think it's just the two of us?

**Comment by curea** [comment]
I am having the same issue, but the messages show on the google messages for desktop web app. All of the contacts show up on the left, and when I click on one it puts the contacts in the top right but no messages show up.

**Comment by infool7** [comment]
I just revo uninstalled and reinstalled and now it's working fine on my laptop :)

**Comment by Nicabus** [comment]
I uninstalled and redownloaded the latest.  Running fine now, but can't seem to find an installer vs standalone anymore.

**Comment by infool7** [comment]
Yes, me too. It's a mystery.

**Comment by curea** [comment]
This worked for me also!

...Aaron
