### ISSUE TITLE
SiriusXM App -- Old build detected error

### ISSUE THREAD

**Issue by barrettwhiteman** [kelyvin/Google-Messages-For-Desktop#61]
![xm](https://user-images.githubusercontent.com/32887250/179517399-962bc4df-5c2a-4c12-aeb4-e69b4b12befa.jpg)

This Error popped up this morning for me on windows 10.
Not sure how big of an issue this is; the app will actually continue to run after dismissing the error.

A past post was closed a year ago, but no resolution.

**Comment by jcarr98** [comment]
I have the same issue using the download from the website. Cloning from the main branch and building using the commands from the readme seemed to fix the issue on both Windows and Linux.

**Comment by localroot4** [comment]
i have the same issue on ubuntu 20 and later:

![Screenshot from 2022-08-14 03-10-41](https://user-images.githubusercontent.com/43405486/184517412-4f520434-8c0a-463b-9af8-a55a891536e9.png)

**Comment by bornakke** [comment]
Using the files in #47 does not seem to work. Maybe it needs to be rebuilt again with this new 'old built detected error' warning?

**Comment by TimCreasman** [comment]
Same thing is happening for the Mac (12.5.1) version:

![Screen Shot 2022-08-25 at 2 47 57 PM](https://user-images.githubusercontent.com/8962809/186744992-55b41765-fd40-4b5a-aa71-a58976b39aeb.png)

**Comment by kelyvin** [comment]
Sorry for the delay everyone. The latest version should now be available here: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.4.0
