### ISSUE TITLE
Google-Messages-Nativefier-11f104 error message

### ISSUE THREAD

**Issue by tjesker** [kelyvin/Google-Messages-For-Desktop#67]
A few days ago I started getting a popup when I open the app that says:

"Old  build detected - This app was built a long time ago.  Nativefier uses the Chrome browser (through Electron), and is insecure to keep using an old version of it.  Please upgrade Nativefier and rebuild this app."  

The issue may have started after upgrading Google4 Chrome to version 108.0.5359.99.  I've observed it on two computers running Windows 10 Pro 22H2.

If I click "OK" the app works fine but I am concerned about it being "insecure".

**Comment by slevit** [comment]
Having same issue on Ubuntu 22.04 
![Screenshot from 2022-12-28 15-25-29](https://user-images.githubusercontent.com/4803896/209868274-5f3b7503-1f6d-48c7-9656-301f0dc88b0f.png)
LTS.

**Comment by kelyvin** [comment]
Sorry about the delay all. Should be updated now here: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.4.1

I seriously need to set up a recurring GitHub action to fix this. I'll get to that....someday. Thanks for your patience!
