### ISSUE TITLE
Old build detected

### ISSUE THREAD

**Issue by auronpl315** [kelyvin/Google-Messages-For-Desktop#71]
<img width="1440" alt="Screenshot 2023-04-09 at 21 19 53" src="https://user-images.githubusercontent.com/72985338/230792392-438bc16a-a2bf-424f-9d2a-b3ffba319b5a.png">

**Comment by nuffseth** [comment]
I have this same error. How would be go about fixing this?

**Comment by slevit** [comment]
Same issue - Ubuntu 22.04 LTS.

**Comment by adhillon192** [comment]
> I have this same error. How would be go about fixing this?

I'd love to work with you on this!

**Comment by auronpl315** [comment]
> > I have this same error. How would be go about fixing this?
> 
> I'd love to work with you on this!

desktop % nativefier [https: //www.youtube.com](https://messages.google.com/web/)
--name Google Messages

**Comment by kelyvin** [comment]
Should be fixed now. Sorry about that: https://github.com/kelyvin/Google-Messages-For-Desktop/releases/tag/v1.4.2

**Comment by kelyvin** [comment]
To prevent this from continuously happening, will need some help to setup a quick github action to run this periodically: https://github.com/kelyvin/Google-Messages-For-Desktop/issues/36
